apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: 'prometheus-test-hpa'
  namespace: local
spec:
  maxReplicas: 2
  metrics:
    - pods:
        metricName: custom_value
        targetAverageValue: '10m'
      type: Pods
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: prometheus-test