name: prometheusTest

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: test with Gradle
        run: ./gradlew test
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          kye: ${{ secrets.KEY }}
          script:
            whoami
            sh ./build.sh
            docker run -p 9999:8080 wentjiang/prometheus-test:latest -d