name: prometheusTest

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: test with Gradle
        run: ./gradlew test
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            whoami
            cd /opt/wentjiang/workspace/prometheusTest
            git pull origin main
            ./gradlew bootJar -i --no-daemon
            mv build/libs/*.jar ./app.jar
            APP_NAME=wentjiang/prometheus-test
            TAG="latest"
            IMAGE_NAME="${APP_NAME}:${TAG}"

            docker build -f Dockerfile -t ${IMAGE_NAME} .
            docker tag IMAGE_NAME ${APP_NAME}:latest
            docker run -p 9999:8080 wentjiang/prometheus-test:latest -d